export const resourceTags = [
  "Accessibility",
  "AI",
  "Animations",
  "API",
  "Authentication",
  "Backgrounds",
  "BioTech",
  "Blockchain",
  "Boilerplate",
  "Books",
  "Browser Extensions",
  "Cheatsheets",
  "CMS",
  "Cloud Computing",
  "Color",
  "Components",
  "Concurrency",
  "Computer Vision",
  "CSS",
  "Data Engineering",
  "Data Visualization",
  "Database",
  "Design",
  "Design Systems",
  "DevOps",
  "Distributed Systems",
  "Documentation",
  "Edge Computing",
  "Email",
  "Embedded Systems",
  "Fonts",
  "FPGA",
  "Frameworks",
  "Functional Programming",
  "Generative AI",
  "Icons",
  "Illustrations",
  "Images",
  "Interaction Design",
  "Internet of Things",
  "Kubernetes",
  "Learning & Challenges",
  "Libraries & Packages",
  "Low-Level Programming",
  "Machine Learning",
  "Microservices",
  "Nanotech",
  "Neuromorphic Computing",
  "Networking",
  "Open Source",
  "Performance",
  "Prototyping",
  "Quantum Computing",
  "Real-Time Systems",
  "Reinforcement Learning",
  "Robotics",
  "SAAS",
  "Screenshots",
  "Semantic HTML",
  "SEO",
  "Serverless",
  "Snippets & Hooks",
  "Social Media",
  "System Design",
  "Type Systems",
  "Typing",
  "Typography Engineering",
  "UI UX",
  "Video",
  "VS Code Extensions",
  "Web Components",
  "Web Hosting",
  "Web3",
  "WebAssembly",
  "WebGPU",
  "Website Builders",
  "Writing",
  "Youtube Channels"
] as const;




export type ResourceTag = (typeof resourceTags)[number];
