export const resourceTags = [
  "Accessibility",
  "AI",
  "Animations",
  "API",
  "Authentication",
  "Backgrounds",
  "Boilerplate",
  "Books",
  "Browser Extensions",
  "Cheatsheets",
  "CMS",
  "Color",
  "Components",
  "CSS",
  "Data Visualization",
  "Database",
  "Design",
  "Documentation",
  "Email",
  "Fonts",
  "Frameworks",
  "Icons",
  "Illustrations",
  "Images",
  "Learning & Challenges",
  "Libraries & Packages",
  "Open Source",
  "Performance",
  "SAAS",
  "Screenshots",
  "SEO",
  "Snippets & Hooks",
  "Social Media",
  "System Design",
  "Typing",
  "UI UX",
  "Video",
  "VS Code Extensions",
  "Web3",
  "Web Hosting",
  "Website Builders",
  "Writing",
  "Youtube Channels"
] as const;



export type ResourceTag = (typeof resourceTags)[number];
